// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HPathList: typeof import('./src/components/HPathList.vue')['default']
    HServerSelector: typeof import('./src/components/HServerSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel']
    VExpansionPanelContent: typeof import('vuetify/lib')['VExpansionPanelContent']
    VExpansionPanelHeader: typeof import('vuetify/lib')['VExpansionPanelHeader']
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListGroup: typeof import('vuetify/lib')['VListGroup']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSimpleTable: typeof import('vuetify/lib')['VSimpleTable']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsItems: typeof import('vuetify/lib')['VTabsItems']
  }
}
